on:
  push:
  schedule:
    - cron: '*/27 3-21 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    name: Publish rates
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch and prepare
        uses: ./
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
